Repository googleapis/python-dlp, pull requests merged in 2021-04, with the labels that each got.

#119 Example of of Crypto Deterministic Config using https://cloud.google.…
  samples/snippets/deid.py
  samples/snippets/deid_test.py
Labels: api: dlp, cla: yes

#125 chore: start tracking obsolete files
  synth.metadata
Labels: api: dlp, cla: yes, context: full

#127 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#128 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: dlp, cla: yes, context: full, samples
