Repository googleapis/python-dlp, pull requests merged in 2022-06, with the labels that each got.

#395 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: dlp, automerge, size: xs

#396 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: dlp, size: s

#399 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: dlp, size: s

#402 fix(deps): require protobuf<4.0.0 on v1 branch
  setup.py
Labels: api: dlp, size: xs

#401 fix(deps): require protobuf<4.0.0 on v0 branch
  setup.py
Labels: api: dlp, size: xs
